"""empty message

Revision ID: 0ac868364931
Revises: 631fc3f30c61
Create Date: 2021-05-18 08:29:01.118397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ac868364931'
down_revision = '631fc3f30c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dd_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('extraversion', sa.Float(), nullable=True),
    sa.Column('agreeableness', sa.Float(), nullable=True),
    sa.Column('conscientiousness', sa.Float(), nullable=True),
    sa.Column('emotional_stability', sa.Float(), nullable=True),
    sa.Column('intellect_imagination', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_id')
    )
    op.drop_table('dd_profile_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dd_profile_',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('gender', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extraversion', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('agreeableness', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('conscientiousness', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('emotional_stability', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intellect_imagination', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dd_profile__pkey'),
    sa.UniqueConstraint('phone_id', name='dd_profile__phone_id_key')
    )
    op.drop_table('dd_profile')
    # ### end Alembic commands ###
