"""empty message

Revision ID: 283161c42d72
Revises: 045b53174a97
Create Date: 2021-05-18 03:56:41.424735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283161c42d72'
down_revision = '045b53174a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dd_app_usage', sa.Column('category', sa.String(length=500), nullable=True))
    op.drop_column('dd_app_usage', 'app_pkg_cat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dd_app_usage', sa.Column('app_pkg_cat', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('dd_app_usage', 'category')
    # ### end Alembic commands ###
