"""empty message

Revision ID: 7fecf51cff1b
Revises: aa9f7fdfc5d1
Create Date: 2021-05-18 01:52:42.695692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fecf51cff1b'
down_revision = 'aa9f7fdfc5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dd_app_cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dd_app_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dd_app_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dd_app_category_pkey')
    )
    op.drop_table('dd_app_cat')
    # ### end Alembic commands ###
