"""empty message

Revision ID: a7f801f2679b
Revises: 85290b910724
Create Date: 2021-04-01 13:06:49.162852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7f801f2679b'
down_revision = '85290b910724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dd_app_package_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=True),
    sa.Column('package_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dd_app_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('app_pkg_cat', sa.Integer(), nullable=True),
    sa.Column('time_sec', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dd_phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('cpu_utilization', sa.Integer(), nullable=True),
    sa.Column('memory_utilization', sa.Integer(), nullable=True),
    sa.Column('running_apps', sa.Integer(), nullable=True),
    sa.Column('battery_percentage', sa.Integer(), nullable=True),
    sa.Column('battery_state', sa.Integer(), nullable=True),
    sa.Column('phone_model', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_id')
    )
    op.create_table('dd_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('extraversion', sa.Integer(), nullable=True),
    sa.Column('agreeableness', sa.Integer(), nullable=True),
    sa.Column('conscientiousness', sa.Integer(), nullable=True),
    sa.Column('emotional_stability', sa.Integer(), nullable=True),
    sa.Column('intellect_imagination', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_id')
    )
    op.create_table('dd_running_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('running_apps', sa.Integer(), nullable=True),
    sa.Column('app_pkg_cat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dd_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dd_user_xphone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('profile')
    op.drop_table('app_usage')
    op.drop_table('running_apps')
    op.drop_table('app_package_category')
    op.drop_table('user_xphone')
    op.drop_table('phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('os_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cpu_utilization', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memory_utilization', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('running_apps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('battery_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('battery_state', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='phone_pkey'),
    sa.UniqueConstraint('phone_id', name='phone_phone_id_key')
    )
    op.create_table('user_xphone',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_xphone_pkey')
    )
    op.create_table('app_package_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('package_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='app_package_category_pkey')
    )
    op.create_table('running_apps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('running_apps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('app_pkg_cat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='running_apps_pkey')
    )
    op.create_table('app_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('app_pkg_cat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='app_usage_pkey')
    )
    op.create_table('profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gender', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extraversion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agreeableness', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conscientiousness', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('emotional_stability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intellect_imagination', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='profile_pkey'),
    sa.UniqueConstraint('phone_id', name='profile_phone_id_key')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('dd_user_xphone')
    op.drop_table('dd_user')
    op.drop_table('dd_running_apps')
    op.drop_table('dd_profile')
    op.drop_table('dd_phone')
    op.drop_table('dd_app_usage')
    op.drop_table('dd_app_package_category')
    # ### end Alembic commands ###
