"""empty message

Revision ID: d3e73c95b626
Revises: 283161c42d72
Create Date: 2021-05-18 08:08:23.774708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e73c95b626'
down_revision = '283161c42d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dd_profile', sa.Column('username', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dd_profile', 'username')
    # ### end Alembic commands ###
